### PR TITLE
DDF-UI-146 Add error messaging for when bounding box south >= north

### LINKED ISSUE #146: Bounding box searches should be prevented if the south value is greater than the north value
Currently, if a user enters south and north values where south > north, the 2D map incorrectly renders a line. The 3D map takes all the coordinates into an array and renders a PolyLine (where coordinate order doesn't matter), so the correct bounding box is rendered. But both maps should not render anything since the bounding box is invalid. 
If the search is executed with the invalid bounding box, it returns results within the intended bounding box because the search uses a polygon (where again, coordinate order doesn't matter). But with the recent UX changes to geo searches, we're moving more towards error handling being the responsibility of the user with an increase in specific inline errors. Therefore the search should be prevented from executing if the bounding box is invalid due to the south value being greater than the north value.

### PR DESCRIPTION
**Pull request by hayleynorton**
#### What does this PR do?
This PR adds inline and pop-up error messaging for when a bounding box's south value is greater than or equal to the north value. It prevents the invalid bounding box from rendering on both maps and prevents the user from executing the search until the error is resolved.
This PR also refactors some of the validation functions in dms-utils and dd-utils
#### Who is reviewing it? 
@andrewzimmer @cassandrabailey293 @zta6 
#### Select relevant component teams: 
@codice/ui 
#### Ask 2 committers to review/merge the PR and tag them here.
@bdeining
@shaundmorris 
#### How should this be tested?
- Create an anyGeo search with a bounding box 
- Enter south values that are less than or equal to a north value
- Verify that you see the inline error message (first screenshot below)
- Switch to different coordinate systems and verify the message persists (USNG and UTM messages will be worded differently; see second screenshot below)
- Verify that nothing is rendered on the map (both 2D and 3D)
- Attempt to execute the search and verify that you see the generic "bounding box is invalid" pop-up error message
- Verify there is no regression with previous inline & pop-up error messaging related to bounding box geo searches
#### What are the relevant tickets?
Fixes: #146
G-7959
#### Screenshots
image
image
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

File: ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/validation.tsx [hunk 1]
```diff
@@ -263,6 +270,60 @@ function validateLinePolygon(mode: string, currentValue: string) {
...
+        })
+      : null
+    south = coordinateSouth
+      ? dmsCoordinateToDD({
+          ...coordinateSouth,
+          direction: value.dmsSouthDirection,
+        })
+      : null
+  } else if (value.usng) {
+    const upperLeftCoord = converter.USNGtoLL(value.upperLeft, true)
```
Comment (zta6) [inline ui-frontend/packages/catalog-ui-search/src/main/webapp/react-component/utils/validation/validation.tsx]:
```
    const upperLeftCoord = converter.USNGtoLL(value.upperLeft, true)
    const lowerRightCoord = converter.USNGtoLL(value.lowerRight, true)
    north = upperLeftCoord.lat
    south = lowerRightCoord.lat
```
✏️  super nit-pick but it might look a shade cleaner like this

**Review by zta6 — APPROVED** [review]

**Review by shaundmorris — APPROVED** [review]

**Comment by andrewzimmer** [comment]
changes hero'd here https://github.com/codice/ddf/pull/5958#issuecomment-616772270

**Review by bdeining — APPROVED** [review]
